api:
  environment:
  - CONCEPTNET_DB_HOSTNAME=db
  - CONCEPTNET_BUILD_DATA=/data/conceptnet
  - CONCEPTNET_DATA=/data/conceptnet
  - CONCEPTNET_RATE_LIMITING=0
  image: rspeer/conceptnet:5.5.5
  links:
  - db
  ports:
  - 8077:80
  volumes:
  - data:/data/conceptnet
  - cache:/data/nginx
db:
  environment:
  - POSTGRES_DB=conceptnet5
  expose:
  - '5432'
  image: rspeer/conceptnet-data:5.5.5
  restart: always
  volumes:
  - data:/data/conceptnet
  - psql:/var/lib/postgresql/data

